export const months = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "Mei",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
];

export const dataCPrkp = [
  {
    id: "1",
    ro: "Menjaga Persatuan dan Kesatuan NKRI bagi Aparatur",
    tagging: ["Pengendalian jarak jauh", "Pengendalian jarak dekat"],
    category: "Proyek BUMN",
    responsible: "Kementerian Koordinator Bidang Politik, Hukum, dan Keamanan",
    fundSource: "APBN",
    children: [
      {
        id: 1,
        kegiatan:
          "lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, cumque lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, cumque",
        target: "10",
        satuan: "Juta",
        color: "blue",
        months: [
          {
            name: "jan",
            aktivitas: "Fasilitasi revitalisasi",
            target: "30",
            satuan: "%",
          },
          {
            name: "feb",
            aktivitas: "Aktualisasi nilai",
            target: "55",
            satuan: "%",
          },
          {
            name: "mar",
            aktivitas: "Modernisasi sistem",
            target: "11",
            satuan: "%",
          },
          {
            name: "apr",
            aktivitas: "Akar budaya",
            target: "11",
            satuan: "%",
          },
          null,
          null,
          {
            name: "jul",
            aktivitas: "Fasilitasi revitalisasi",
            target: "30",
            satuan: "%",
          },
          {
            name: "aug",
            aktivitas: "Aktualisasi nilai",
            target: "55",
            satuan: "%",
          },
          null,
          null,
          null,
          null,
        ],
      },
      {
        id: 2,
        kegiatan: "Testing 2",
        target: "10",
        satuan: "Juta",
        color: "red",
        months: [
          null,
          null,
          null,
          null,
          {
            name: "mei",
            aktivitas: "Aktualisasi nilai",
            target: "55",
            satuan: "%",
          },
          {
            name: "jun",
            aktivitas: "Modernisasi sistem",
            target: "11",
            satuan: "%",
          },
          {
            name: "jul",
            aktivitas: "Akar budaya",
            target: "55",
            satuan: "%",
          },
          null,
          null,
          null,
          null,
        ],
      },
      {
        id: 3,
        kegiatan: "Testing 3",
        target: "10",
        satuan: "Juta",
        color: "orange",
        months: [
          null,
          null,
          null,
          null,
          null,
          {
            name: "jun",
            aktivitas: "Fasilitasi revitalisasi",
            target: "30",
            satuan: "%",
          },
          {
            name: "jul",
            aktivitas: "Aktualisasi nilai",
            target: "55",
            satuan: "%",
          },
          null,
          null,
          null,
          {
            name: "nov",
            aktivitas: "Fasilitasi revitalisasi",
            target: "30",
            satuan: "%",
          },
          {
            name: "dec",
            aktivitas: "Aktualisasi nilai",
            target: "55",
            satuan: "%",
          },
        ],
      },
    ],
  },
  {
    id: "2",
    ro: "Persatuan yang dipimpin oleh hikmat kebijaksanaan dalam permusyawaratan/perwakilan",
    tagging: ["Peraturan Baru", "Peraturan Lama"],
    category: "Proyek Belanja K/L",
    responsible: "Kementerian Dalam Negeri",
    fundSource: "Pemerintah Pusat",
    children: [
      {
        id: 1,
        kegiatan: "Testing",
        target: "10",
        satuan: "%",
        color: "blue",
        months: [
          {
            name: "jan",
            aktivitas: "Fasilitasi revitalisasi",
            target: "30",
            satuan: "%",
          },
          {
            name: "feb",
            aktivitas: "Aktualisasi nilai",
            target: "55",
            satuan: "%",
          },
          null,
          null,
          null,
          null,
          null,
          null,
          {
            name: "sep",
            aktivitas: "Modernisasi sistem",
            target: "11",
            satuan: "%",
          },
          {
            name: "oct",
            aktivitas: "Akar budaya",
            target: "55",
            satuan: "%",
          },
          null,
        ],
      },
      {
        id: 2,
        kegiatan: "Testing 2",
        target: "10",
        satuan: "Miliar",
        color: "orange",
        months: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          {
            name: "oct",
            aktivitas: "Modernisasi sistem",
            target: "11",
            satuan: "Triliun",
          },
          {
            name: "nov",
            aktivitas:
              "lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, cumque",
            target: "55",
            satuan: "%",
          },
          null,
        ],
      },
    ],
  },
];
